{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubegate-agent
  labels:
    app: kubegate-agent
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubegate-agent-admin-binding
  labels:
    app: kubegate-agent
subjects:
- kind: ServiceAccount
  name: kubegate-agent  
  namespace: default  # Replace with the namespace of your ServiceAccount
roleRef:
  kind: ClusterRole
  name: cluster-admin  # Use the built-in cluster-admin role
  apiGroup: rbac.authorization.k8s.io
