{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubegate-agent
  labels:
    app: kubegate-agent
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubegate-agent-admin-binding
  labels:
    app: kubegate-agent
subjects:
- kind: ServiceAccount
  name: kubegate-agent  
  namespace: kubegate
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: kubegate-agent-role
# rules:
#   - apiGroups: [""]
#     resources: ["pods", "services", "replicationcontrollers"]
#     verbs: ["get", "list", "watch"]
#   - apiGroups: ["apps"]
#     resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
#     verbs: ["get", "list", "watch"]
#   - apiGroups: ["batch"]
#     resources: ["jobs", "cronjobs"]
#     verbs: ["get", "list", "watch"]
#   - apiGroups: ["autoscaling"]
#     resources: ["horizontalpodautoscalers"]
#     verbs: ["get", "list", "watch"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: kubegate-agent-rolebinding
#   namespace: kubegate
# subjects:
#   - kind: ServiceAccount
#     name: kubegate-agent
#     namespace: kubegate
# roleRef:
#   kind: ClusterRole
#   name: kubegate-agent-role
#   apiGroup: rbac.authorization.k8s.io
