current-context: dev
contexts:
  - name: dev
    rabbitmq-url: amqp://guest:guest@localhost:5672/
    command-queue: kubegate-commands-dev
    reply-queue: reply-queue-dev
  - name: prod
    rabbitmq-url: amqp://user:pass@prod-rabbitmq:5672/
    command-queue: kubegate-commands-prod
    reply-queue: reply-queue-prod
