name: KubeGate Release 
  release:
    name: Create Release
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Bump Version
        id: version
        uses: mathieudutour/github-tag-action@v6
        with:
          default: patch

      - name: Build Binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/kubegate-linux-amd64 main.go
          GOOS=darwin GOARCH=amd64 go build -o dist/kubegate-darwin-amd64 main.go
          GOOS=windows GOARCH=amd64 go build -o dist/kubegate-windows-amd64.exe main.go

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/kubegate-linux-amd64
            dist/kubegate-darwin-amd64
            dist/kubegate-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}